# Generated by Django 3.2.4 on 2022-02-01 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_of_category',
            field=models.ImageField(default=datetime.datetime(2022, 2, 1, 18, 29, 38, 166143, tzinfo=utc), upload_to='category_images/'),
            preserve_default=False,
        ),
    ]
